# Generated by Django 3.0.6 on 2020-05-31 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urlImage', models.CharField(max_length=200)),
                ('urlProject', models.CharField(max_length=200)),
                ('nameProject', models.CharField(max_length=200)),
            ],
        ),
    ]
