# Generated by Django 3.0.6 on 2020-05-31 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myProjects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myproject',
            name='urlImage',
            field=models.ImageField(blank=True, upload_to='myProjects/%Y/%m/%d'),
        ),
    ]
