# Generated by Django 3.0.6 on 2020-05-31 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myProjects', '0002_auto_20200531_2229'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myproject',
            old_name='urlImage',
            new_name='image',
        ),
    ]
