# Generated by Django 3.0.6 on 2020-06-01 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myProjects', '0003_auto_20200531_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myproject',
            name='image',
            field=models.ImageField(blank=True, upload_to='MyProjects/static/images'),
        ),
    ]
